### ISSUE TITLE
Double click on issue does not open class

### ISSUE THREAD

**Issue by aamarber** [jmecosta/VSSonarQubeExtension#114]
When I updated the plugin today, if I double click on an issue does not open the class that has the issue. Also, if I make a right click on the issue and go to Open -> Visual Studio there's an exception. I attach the screenshot.

Please, it's an important bug because it's really annoying to open the class and all the stuff. Double-clicking was too great to lose it :(

![captura](https://cloud.githubusercontent.com/assets/5449797/7650633/bed2d3a2-faf8-11e4-8729-93f7d9bad713.PNG)

**Comment by jmecosta** [comment]
hi, try to update to version 3.1.2. there was a small issue with 3.1.1

**Comment by aamarber** [comment]
My current version is 3.1.2

**Comment by jmecosta** [comment]
oh crap.... can you  tell me your environment. also its everything else running (do you have markings in text and so on)?

**Comment by aamarber** [comment]
Of course, I have Visual Studio 2013 Ultimate and yes, everything is working (even Stylecop analysis locally) but don't know why the files with issues don't open when I double click at the issue. If you need some more info just ask for it ;)

**Comment by jmecosta** [comment]
hum, thats very odd. i dont have box with ultimate alone only professional. one thing you can try is to wipe  all the configuration in general settings -> reset all changes. if that does not work, i can try to prepare a debug version for you to try. this new version did not really touched this so i am puzzeled

**Comment by jmecosta** [comment]
@aamarber are you by the way associated with a sonar project in server, i was able to get a crash. but i supposed it was also present in 3.1.0

**Comment by jmecosta** [comment]
@aamarber can you try with this
https://github.com/jmecosta/VSSonarQubeExtension/releases/tag/3.1.3

**Comment by aamarber** [comment]
Sorry, at the weekend I didn't read your updates but I have tried the version 3.1.3 and it doesn't open the file buut when I right click on the issue -> open -> Visual Studio there's no exception... but does not open the file neither.

If it helps, I have a project associated. Also I have tried disabling and enabling the plugin, enabling the debug mode but nothing helps. What can I do to help you?

**Comment by jmecosta** [comment]
can you send me a sample of a project that causes this, i need the
sonar.properties file used to run a full analysis.

**Comment by aamarber** [comment]
Hmph that I can't do it, because the project is a product of my company and I can't create a sample project because I don't have access to the sonar server :(

**Comment by jmecosta** [comment]
do you have sonar-project.properties in your project root, i suspect you
dont. this new version requires this file to retrive the keys.

**Comment by aamarber** [comment]
Nope I don't have it and yes, probably it's a problem cause every time I open the VS the settings of the plugin are lost. It's not auto-generated? Can you provide me with a sample .properties file to test if it's the problem?

**Comment by jmecosta** [comment]
try one of the sample projects in
https://github.com/jmecosta/VSSonarQubeExtension/tree/master/sampleProjects

all those are supported types of projects.

**Comment by aamarber** [comment]
I put a .properties file and now my credentials and settings remain after closing the VS, but the double click still does not work. This is the content of the file "sonar-project.properties" inside my solution folder (I have tried removing the postgres settings because I don't have full access to the sonar remote server but didn't work neither):

sonar.jdbc.url=jdbc:postgresql://localhost:5432/sonar
sonar.jdbc.driver=org.postgresql.Driver
sonar.host.url=http://sonar.iti.upv.es/sonar

sonar.projectKey=AB:altai_evolution
sonar.projectName=altai_evolution
sonar.projectVersion=1
sonar.projectDescription=
sonar.sources=./

sonar.visualstudio.enable=true

**Comment by jmecosta** [comment]
Try disabling the visual studio.  You can post the keys that you find in
the issues tab. I likely can tell you what type of properties file to use

**Comment by aamarber** [comment]
I have changed the properties and now the associated project works too when closing-reopening but still the double-click does not open the file. Could it be because of the sources key? Right now I have this at my properties:

sonar.host.url=http://sonar.iti.upv.es/sonar

sonar.projectKey=com.ITI:altai_evolution
sonar.projectName=altai_evolution
sonar.projectVersion=1
sonar.projectDescription=
sonar.sources=.

sonar.visualstudio.enable=false

**Comment by jmecosta** [comment]
Not sure, if you can provide the key of one of the issues that is retrieved
from server we might no more. If you cannot give that you can replace the
names with some dummy stuff I just need to structure of the key. It might
be that in server they are using some multi module approach that is not in
one of the samples

**Comment by jmecosta** [comment]
Any way I will try to guess from the project association if we can retrieve
the key translation. For next version tought

**Comment by aamarber** [comment]
Hmm if I understood you, you want to see the issues tab to see which data is provided from server to check if there's something strange? I can provide you with an screenshot of the data the only thing I can't provide is the project solution (is not mine :P). Is it what you wanted??
![ss](https://cloud.githubusercontent.com/assets/5449797/7682223/d2ecba08-fd76-11e4-9204-fc0fafddd6e3.png)

**Comment by jmecosta** [comment]
you have this type of keys in server:

com.ITI:altai_evoluation:Altai.Core.Presentation:Views/Controls/LayoutToolBar.xaml 

i suspect you have some modules or sonar.visualstudio.enable=true

Altai.Core.Presentation is a csproj, so double clicking on that with sonar.visualstudio.enable=true will translate into 

<SolutionDir>\Altai.Core.Presentation\Views\Controls\LayoutToolBar.xaml 

can you verify that

**Comment by aamarber** [comment]
With modules do you refer to separated projects inside the solution? If that's what you are referring, yes we have modules/projects.

How can I verify that double clicking translates to that? When I double click on the issue nothing happens, there's no output window or something similar. Also I have tried with sonar.visualstudio.enable=true and sonar.visualstudio.enable=false

Surprisingly, I have tried to right click on an issue -> Open -> Browser and now it opens with no exception thrown. Unhappily it's not the case of Open -> Visual Studio, that still not works.

**Comment by jmecosta** [comment]
I try to prepare a version that display the translated key into output

**Comment by jmecosta** [comment]
@aamarber can you check with this: https://github.com/jmecosta/VSSonarQubeExtension/releases/tag/4.0.0-Beta-1 perhapps now its fixed

**Comment by binamrathapa** [comment]
This problem has also faced to me in vs2013.
When click on .cs file.
![double_click_issue](https://cloud.githubusercontent.com/assets/13516220/9354781/01793062-4693-11e5-9c8d-5f313752ea68.png)

**Comment by jmecosta** [comment]
I will provide soon with a new beta, I've changed some things in here

**Comment by jmecosta** [comment]
@binamrathapa beta-2 is not available

**Comment by jmecosta** [comment]
@binamrathapa 4.0.1 has been released, it should improve this problem

**Comment by binamrathapa** [comment]
Hi,
Now, it crashed when I associated project. There are no projects list in dropdown

**Comment by jmecosta** [comment]
Hi,

Can you provide the stack trace from the event log.

**Comment by jmecosta** [comment]
@binamrathapa  i suppose, you were not logged in, after that the association window pop up. There were no projects and you press associate and it crash...? got it, will fix straigh away

**Comment by binamrathapa** [comment]
HI,
Yes, But how can i solve this issue?

**Comment by jmecosta** [comment]
@binamrathapa I just updated the extension in both gallery and GitHub. please let me know if it helps. Regarding the empty project list, I suppose you need to to go options and sign in again

**Comment by binamrathapa** [comment]
Hi,
When I associate project then it crashes.

**Comment by jmecosta** [comment]
By any chance you use the new msbuild runner? And is the project you are
associating marked in red?

What is your visual studio 2012 version?

**Comment by binamrathapa** [comment]
Selected project is highlighted but not marked in red. Visual studio is 2013 community version

**Comment by jmecosta** [comment]
ok, i try to try this in 2013 community version. see if thats the reason, can you try in another version perhapps?

**Comment by jmecosta** [comment]
@binamrathapa i was able to replicate the beahviour in 2013, i will look into it. Thanks for the report...

**Comment by jmecosta** [comment]
@binamrathapa in the server address are you having a trailing / ? Can you remove and try again, apparently this / is causing settings to be cleaned...

**Comment by jmecosta** [comment]
@binamrathapa hopefully i got it right now, https://github.com/jmecosta/VSSonarQubeExtension/releases/tag/4.0.2-beta-1

**Comment by binamrathapa** [comment]
It is still same problem. I removed / and install new version. I tested in vs2012 and vs2013. project lists are displayed and project selected then click on associate button. VS crashed.

**Comment by jmecosta** [comment]
Can you get me the error from event log of windows? By the way do you have
4.6 .net

**Comment by binamrathapa** [comment]
Faulting application name: devenv.exe, version: 12.0.31101.0, time stamp: 0x54548724
Faulting module name: KERNELBASE.dll, version: 6.3.9600.17415, time stamp: 0x54504ade
Exception code: 0xe0434352
Fault offset: 0x00014598
Faulting process id: 0x1600
Faulting application start time: 0x01d0e47537a87ad0
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: cb2f217c-5068-11e5-80fc-005056a10c17
Faulting package full name: 
Faulting package-relative application ID:

**Comment by jmecosta** [comment]
Is that the only entry? usually those are coming in bunches. Usually the previous one revers to the relevant failure

**Comment by binamrathapa** [comment]
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException
Stack:
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at GalaSoft.MvvmLight.Helpers.WeakAction.Execute()
   at GalaSoft.MvvmLight.Command.RelayCommand.Execute(System.Object)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by jmecosta** [comment]
Ok thats weird, the only thing familiar in that stack trace is the
galasfoft. perhaps there is another extension using a different version of
the mvvmlight that is causing this.

Can you shared what extensions do you have installed?

**Comment by binamrathapa** [comment]
In project list, there is one project marked in red by default, which was not selected. why this occurs?

**Comment by jmecosta** [comment]
it happens because it considers it as a feature branch project. when this happens there should be additional branches showing up in the right. if try to select that one and if there is no branch in the right than it will complain that you need to choose the branch project.

ive recently realized that some project can have space and not being branch projects. i will need to fix this in #137 

Either way, is this the one causing the crash?

**Comment by jmecosta** [comment]
Please reopen if still a issue
